### ISSUE TITLE
How can I train my dataset?

### ISSUE THREAD

**Issue by sungonce** [feixh/GeoSup#1]
I want to train my own dataset with this network, but I have some problem with training..
maybe it's because of the wrong pose setting.

what is wgc and rg exactly in pose pkl file?  How can i define them in my own dataset? I have (x,y,z) point and unit direction vector of each images with world coordinate.

**Comment by feixh** [comment]
Rg is a 3x3 rotation matrix to bring the direction of gravity from the inertial frame (or world frame if the world frame coincides with the inertial frame) to camera frame. In the figure you showed, let's say gravity has direction a=(0, 0, -1) in the inertial/world frame meaning it points to the negative z axis. In your camera frame, the direction of gravity points to the positive y direction, i.e., having coordinates b=(0, 1, 0). Then, Rg is such that b=Rg a. You can find Rg is 
[[1, 0, 0], 
[0, 0, -1], 
[0, 1, 0]] in this case.

**Comment by sungonce** [comment]
thanks! I understand about Rg with your kind explanation :D
And how about wgc? What is wgc exactly(what is the base coordinate system of wgc) and how can i make it with given information?

**Comment by feixh** [comment]
By "wgc", do you mean g_{wc}? That's the rigid body transformation from camera (c) at current time step to world (w) with world being the inertial/spatial frame. If you have a VIO system, the world frame should be accordingly defined. In the example above, if Rg defined in world frame reads Rg_in_world = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]. And the rotation part of g_{wc} is R_{wc} = [[1, 0, 0], [0, 0, 1], [0, -1, 0]]. 
So to bring gravity to your current camera frame you have Rg_in_camera = R_{wc}.inv() * Rg_in_world
